### ISSUE TITLE
Make Pokéstop Gym and EX Gym highlight colors configurable

### ISSUE THREAD

**Issue by 5310** [PoGOHWH/iitc-ce-pogo-s2#1]

**Comment by Deses** [comment]
If you wanna change the colors, edit the source by looking for these:

**Stop:**
> Search "#13C193" and change it to  "#41ACE1" or whatever you like.
> It should be around line 2022 and 2024.

**Gym:**
> Search "black" and change it to  "#F61208" or whatever you like.
> It should be around line 2036 and 2038.

**If you want to change the fill color of a raid ex:**

> Search "#FF7BEE" and change it to  "#FACA38" or whatever you like.
> It should be around line 2038.

**Comment by 5310** [comment]
> If you wanna change the colors, edit the source by looking for these...

I was just coming to post these, but you already got to it I see :D

I was kinda hoping to expose these colors to the IITC interface, but people will only really need to customize them once so I guess it's fine to edit them in the source, right?

**Comment by Deses** [comment]
You should definitely add something to change the colors via the web interface, and also save them to some cookie, storage or something else because I'm pretty sure that whenever you update the script, my color changes will get overwritten. :(

**Comment by eengnr** [comment]
PR #9 fixes this issue.
