### ISSUE TITLE
Make PoGO markers larger on mobile so that they cover Portals like on desktop

### ISSUE THREAD

**Issue by 5310** [PoGOHWH/iitc-ce-pogo-s2#2]
Tried a blind-faith implementation [here](https://github.com/PoGOHWH/iitc-ce-pogo-s2/blob/pogohwh/s2check.user.js#L1814), and it seems to make no difference on IITC-CE on Android.

Case in point, _uuugleh_: 
![image](https://user-images.githubusercontent.com/112914/68994092-f1a4f580-08a4-11ea-8eae-3d1a0611a493.png)

**Comment by PoGOHWH** [comment]
Turns out, IITC had [remote debugging enabled](navigator.userAgent.match(/Android.*Mobile/) ? 1.3 : 1) already. The original `isIITCm()` function simply does not work because it's too strict, at least for IITC-CE. Went with the simplest solution for now.
