### ISSUE TITLE
Just wanted to say... amazing fork!!!

### ISSUE THREAD

**Issue by Deses** [PoGOHWH/iitc-ce-pogo-s2#7]
The original scrip is great but it's sooo sloooow. Your modifications are awesome! It works so much better now. :)

**Comment by 5310** [comment]
Thank you very much :blush: 

I'm glad it's still working, because you see we haven't been able to work on mapping our city's PoI's pretty much since Wayfarer opened up to all PoGO players and the influx of new PoIs became too much to handle (and ofc, then Covid happened :)

**Comment by Deses** [comment]
> we haven't been able to work on mapping our city's PoI's pretty much since Wayfarer opened up to all PoGO players and the influx of new PoIs became too much to handle (and ofc, then Covid happened :)

Wayfarer is full of trash submissions now, I agree. It takes months to get anything reviewed if I'm not upgrading the submissions... so yeah, it's a drag now.

**Comment by 5310** [comment]
We didn't really use to have a lot of trash even after PoGO submissions opened. And during the lockdown the reviews went up a lot too, and that helped. If anything, it's going from single digit PoI within visible range to triple is what made keeping up harder :D 

Ofc, after the initial Covid rush known bad actors started submitting fakes again, and now it's all clogged up :|
