### ISSUE TITLE
"Error initializing ThisIsPogo"

### ISSUE THREAD

**Issue by Deses** [PoGOHWH/iitc-ce-pogo-s2#8]
Copypasting the original issue here so @PoGOHWH is in the loop.
Original issue: https://gitlab.com/AlfonsoML/pogo-s2/-/issues/68

> I'm getting this error message when opening the Intel site. It was working fine yesterday so Niantinc must have changed something.
> 
> ![image](https://user-images.githubusercontent.com/1654959/115129356-6376f680-9fe5-11eb-81c7-c2a596676500.png)
> 
> The only difference seems to be that the Ingress triangular areas and lines are displayed rather than be hidden. Everything else seems to be working so far.

**Comment by 5310** [comment]
:thinking: I can't really reproduce this error with either this fork or the original. 

Do you have any other addons installed? Any notable errors in the browser console?

**Comment by elles93** [comment]
Hello, I have this issue too.

Error initializing ThisIsPogo: TypeError: window.updateDisplayedLayerGroup is not a function
